name: integration-test

on:
  push:
    branches:
      - main
  pull_request:

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
        with:
          distribution: 'zulu'
          java-version: 19

      - name: Gradle cache
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2

      - name: integration test
        id: integration-test
        run: |
          cd include-build
          ./gradlew roborazzi-gradle-plugin:check --stacktrace

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        if: ${{ always() }}
        with:
          name: test-reports
          path: include-build/roborazzi-gradle-plugin/build/reports
          retention-days: 30

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        if: ${{ always() }}
        with:
          name: test-test-results
          path: include-build/roborazzi-gradle-plugin/build/test-results
          retention-days: 30
