name: StoreScreenshot

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  store-screenshot-test:
    runs-on: macos-latest
    timeout-minutes: 20

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up JDK 17
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: temurin
          java-version: 17

      # Better than caching and/or extensions of actions/setup-java
      - name: Setup Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629 # v2.4.2
        with:
          gradle-version: wrapper

      - name: record screenshot
        id: record-test
        run: |
          cd include-build; 
          ./gradlew roborazzi-core:test
          cd ..
          ./gradlew recordRoborazziDebug recordRoborazziDesktop recordRoborazziJvm recordRoborazziIosX64 --stacktrace

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        if: ${{ always() }}
        with:
          name: screenshot
          path: |
            **/build/outputs/roborazzi
          retention-days: 30

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        if: ${{ always() }}
        with:
          name: screenshot-reports
          path: |
            **/build/reports
            **/build/outputs/roborazzi
          retention-days: 30

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        if: ${{ always() }}
        with:
          name: screenshot-test-results
          path: |
            **/build/test-results
          retention-days: 30
